export default function PrivacyPolicyPage() {
  return (
    <div className="card legal-page">
      <span className="legal-page__eyebrow">Legal</span>
      <h2>Privacy Policy</h2>
      <p className="muted">Last updated: March 14, 2026</p>

      <section>
        <h3>1. Controller and scope</h3>
        <p>
          This Privacy Policy explains how personal data is processed when you use this CalendarSync Cloud deployment
          (the &quot;Service&quot;). The controller is the operator of this deployment.
        </p>
        <p>
          The policy applies to the web application, API, and worker services used to connect Google accounts and run
          calendar synchronization rules.
        </p>
      </section>

      <section>
        <h3>2. Data we process</h3>
        <p>Depending on your use of the Service, we process the following categories of data:</p>
        <ul>
          <li>
            Account and identity data: Google account subject ID, email address, and basic profile name used for sign
            in and account linking.
          </li>
          <li>
            Connection metadata: linked Google account identifiers, linked calendar IDs, calendar summaries, primary
            flags, and access roles.
          </li>
          <li>
            OAuth credentials: Google OAuth access and refresh tokens stored in encrypted form in the database.
          </li>
          <li>
            Sync configuration: rule names, source and target calendars, schedule, payload mode, direction, filters,
            transformations, dry-run settings, and execution settings.
          </li>
          <li>
            Run and operations data: run status, trigger type, timestamps, summaries, and error messages needed to
            operate and troubleshoot synchronization.
          </li>
          <li>
            Calendar event content: event data read from source calendars and written to target calendars to execute
            rules you configured.
          </li>
          <li>
            Technical request data: server-side request metadata and infrastructure logs generated by hosting providers.
          </li>
        </ul>
      </section>

      <section>
        <h3>3. Sources of data</h3>
        <p>We receive personal data directly from you and from Google when you connect accounts, including:</p>
        <ul>
          <li>Google Sign-In via NextAuth on the frontend.</li>
          <li>Google OAuth and Google UserInfo endpoint during account linking.</li>
          <li>Google Calendar API responses used to list calendars and run synchronization.</li>
          <li>Data you submit when creating or editing sync rules.</li>
        </ul>
      </section>

      <section>
        <h3>4. Purposes and legal bases</h3>
        <p>We process personal data for the following purposes:</p>
        <ul>
          <li>Provide authentication and account access.</li>
          <li>Link Google accounts and maintain active calendar connections.</li>
          <li>Execute scheduled and manual synchronization and cleanup runs.</li>
          <li>Store rule definitions and run history.</li>
          <li>Protect the Service against abuse and unauthorized access.</li>
          <li>Maintain security, reliability, and performance.</li>
        </ul>
        <p>
          Under the GDPR, processing is typically based on Art. 6(1)(b) (performance of a contract) and Art. 6(1)(f)
          (legitimate interests in secure and reliable operation). Where consent is required by law, Art. 6(1)(a)
          applies.
        </p>
      </section>

      <section>
        <h3>5. Google permissions and calendar content</h3>
        <p>
          The Service requests Google scopes needed to identify your account and synchronize calendars, including
          OpenID, email/profile information, calendar read access, and calendar events write access.
        </p>
        <p>
          Calendar event data is processed only to run the sync rules you enable (for example, full-details sync or
          busy-only sync). We do not sell calendar content or use it for advertising.
        </p>
      </section>

      <section>
        <h3>6. Storage, hosting, and processors</h3>
        <p>This deployment uses third-party infrastructure providers to operate the Service, including:</p>
        <ul>
          <li>Neon/PostgreSQL for application data storage.</li>
          <li>Google Cloud services for API/worker execution, scheduling, and optional key management.</li>
          <li>Vercel for frontend hosting.</li>
          <li>Google APIs for identity and calendar operations.</li>
        </ul>
        <p>
          These providers process data as service providers/processors to deliver infrastructure and platform
          capabilities.
        </p>
      </section>

      <section>
        <h3>7. Security measures</h3>
        <p>We apply technical and organizational measures designed to protect personal data, including:</p>
        <ul>
          <li>Encryption of stored OAuth tokens (envelope encryption with AES-GCM and key versioning).</li>
          <li>Use of Google Cloud KMS when configured, with support for key rotation/migration.</li>
          <li>Restricted internal API endpoints protected by shared secrets and service authentication.</li>
          <li>Transport security (HTTPS/TLS) for data in transit.</li>
        </ul>
      </section>

      <section>
        <h3>8. Cookies and session data</h3>
        <p>
          The frontend uses authentication/session mechanisms provided by NextAuth to keep you signed in. This may
          involve strictly necessary cookies or similar session storage required to operate login and account sessions.
        </p>
      </section>

      <section>
        <h3>9. Data retention and deletion</h3>
        <p>
          We retain personal data for as long as needed to provide the Service, comply with legal obligations, resolve
          disputes, and enforce agreements.
        </p>
        <p>
          If you remove a linked Google connection, related data connected through foreign-key relationships is deleted
          from operational tables (including associated encrypted token records and dependent sync data).
        </p>
        <p>
          If you delete a sync rule, related run records and dependent rule data are removed according to database
          constraints. If you need full account deletion, contact the deployment operator.
        </p>
      </section>

      <section>
        <h3>10. International transfers</h3>
        <p>
          Depending on the region and provider configuration, personal data may be processed in countries outside your
          own jurisdiction. Where required, providers are expected to rely on appropriate transfer safeguards under
          applicable data protection law.
        </p>
      </section>

      <section>
        <h3>11. Your rights</h3>
        <p>
          Subject to applicable law (including GDPR where applicable), you may have rights to access, rectify, erase,
          restrict, or object to processing, withdraw consent, and request data portability. You may also have the
          right to lodge a complaint with a supervisory authority.
        </p>
      </section>

      <section>
        <h3>12. Children</h3>
        <p>
          The Service is not designed specifically for children. If you believe personal data of a child was processed
          without appropriate authorization, contact the deployment operator.
        </p>
      </section>

      <section>
        <h3>13. Changes to this policy</h3>
        <p>
          We may update this Privacy Policy from time to time. The current version is published on this page with the
          &quot;Last updated&quot; date.
        </p>
      </section>

      <section>
        <h3>14. Contact</h3>
        <p>
          For privacy requests (including access or deletion), contact the operator of this specific CalendarSync Cloud
          deployment through the support channel provided with the service.
        </p>
      </section>
    </div>
  );
}
